### ISSUE TITLE
RuntimeError: failed to load voice "ja"

### ISSUE THREAD

**Issue by fandongminghitmt** [AIFSH/MaskGCT-ComfyUI#3]
Manager

1

节点库
搜索节点...
2024-11-07 23:22:35,577 - root - INFO - Total VRAM 16376 MB, total RAM 65264 MB
2024-11-07 23:22:35,578 - root - INFO - pytorch version: 2.5.1+cu121
2024-11-07 23:22:35,578 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-07 23:22:35,578 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : cudaMallocAsync
2024-11-07 23:22:36,252 - root - INFO - Using pytorch cross attention
2024-11-07 23:22:37,072 - root - INFO - Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
2024-11-07 23:22:37,876 - root - INFO - [Prompt Server] web root: C:\Users\fando\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.36
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path checkpoints C:\Users\fando\Documents\ComfyUI\models/checkpoints/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path classifiers C:\Users\fando\Documents\ComfyUI\models/classifiers/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path clip C:\Users\fando\Documents\ComfyUI\models/clip/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path clip_vision C:\Users\fando\Documents\ComfyUI\models/clip_vision/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path configs C:\Users\fando\Documents\ComfyUI\models/configs/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path controlnet C:\Users\fando\Documents\ComfyUI\models/controlnet/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path diffusers C:\Users\fando\Documents\ComfyUI\models/diffusers/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path diffusion_models C:\Users\fando\Documents\ComfyUI\models/diffusion_models/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path embeddings C:\Users\fando\Documents\ComfyUI\models/embeddings/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path gligen C:\Users\fando\Documents\ComfyUI\models/gligen/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path hypernetworks C:\Users\fando\Documents\ComfyUI\models/hypernetworks/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path loras C:\Users\fando\Documents\ComfyUI\models/loras/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path photomaker C:\Users\fando\Documents\ComfyUI\models/photomaker/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path style_models C:\Users\fando\Documents\ComfyUI\models/style_models/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path unet C:\Users\fando\Documents\ComfyUI\models/unet/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path upscale_models C:\Users\fando\Documents\ComfyUI\models/upscale_models/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path vae C:\Users\fando\Documents\ComfyUI\models/vae/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path vae_approx C:\Users\fando\Documents\ComfyUI\models/vae_approx/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path animatediff_models C:\Users\fando\Documents\ComfyUI\models/animatediff_models/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path animatediff_motion_lora C:\Users\fando\Documents\ComfyUI\models/animatediff_motion_lora/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path animatediff_video_formats C:\Users\fando\Documents\ComfyUI\models/animatediff_video_formats/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path ipadapter C:\Users\fando\Documents\ComfyUI\models/ipadapter/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path liveportrait C:\Users\fando\Documents\ComfyUI\models/liveportrait/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path insightface C:\Users\fando\Documents\ComfyUI\models/insightface/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path layerstyle C:\Users\fando\Documents\ComfyUI\models/layerstyle/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path LLM C:\Users\fando\Documents\ComfyUI\models/LLM/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path Joy_caption C:\Users\fando\Documents\ComfyUI\models/Joy_caption/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path sams C:\Users\fando\Documents\ComfyUI\models/sams/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path blip C:\Users\fando\Documents\ComfyUI\models/blip/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path CogVideo C:\Users\fando\Documents\ComfyUI\models/CogVideo/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path xlabs C:\Users\fando\Documents\ComfyUI\models/xlabs/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path instantid C:\Users\fando\Documents\ComfyUI\models/instantid/
2024-11-07 23:22:37,878 - root - INFO - Adding extra search path custom_nodes C:\Users\fando\Documents\ComfyUI\custom_nodes/
2024-11-07 23:22:38,156 - root - INFO - Total VRAM 16376 MB, total RAM 65264 MB
2024-11-07 23:22:38,156 - root - INFO - pytorch version: 2.5.1+cu121
2024-11-07 23:22:38,157 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-07 23:22:38,157 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : cudaMallocAsync
2024-11-07 23:22:41,444 - root - WARNING - Traceback (most recent call last):
  File "C:\Users\fando\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\fando\Documents\ComfyUI\custom_nodes/MaskGCT-ComfyUI\__init__.py", line 25, in <module>
    from models.tts.maskgct.maskgct_utils import *
  File "C:\Users\fando\Documents\ComfyUI\custom_nodes\MaskGCT-ComfyUI\models\tts\maskgct\maskgct_utils.py", line 26, in <module>
    from models.tts.maskgct.g2p.g2p_generation import g2p, chn_eng_g2p
  File "C:\Users\fando\Documents\ComfyUI\custom_nodes\MaskGCT-ComfyUI\models\tts\maskgct\g2p\g2p_generation.py", line 10, in <module>
    from models.tts.maskgct.g2p.utils.g2p import phonemizer_g2p
  File "C:\Users\fando\Documents\ComfyUI\custom_nodes\MaskGCT-ComfyUI\models\tts\maskgct\g2p\utils\g2p.py", line 30, in <module>
    phonemizer_ja = EspeakBackend(
                    ^^^^^^^^^^^^^^
  File "C:\Users\fando\Documents\ComfyUI\python\Lib\site-packages\phonemizer\backend\espeak\espeak.py", line 49, in __init__
    self._espeak.set_voice(language)
  File "C:\Users\fando\Documents\ComfyUI\python\Lib\site-packages\phonemizer\backend\espeak\wrapper.py", line 249, in set_voice
    raise RuntimeError(  # pragma: nocover
RuntimeError: failed to load voice "ja"

2024-11-07 23:22:41,444 - root - WARNING - Cannot import C:\Users\fando\Documents\ComfyUI\custom_nodes/MaskGCT-ComfyUI module for custom nodes: failed to load voice "ja"
2024-11-07 23:22:41,977 - root - WARNING - Skip C:\Users\fando\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\custom_nodes\DesktopSettingsExtension module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
2024-11-07 23:22:41,977 - root - INFO - 
Import times for custom nodes:
2024-11-07 23:22:41,978 - root - INFO -    0.0 seconds: C:\Users\fando\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-07 23:22:41,978 - root - INFO -    0.0 seconds (IMPORT FAILED): C:\Users\fando\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\custom_nodes\DesktopSettingsExtension
2024-11-07 23:22:41,978 - root - INFO -    0.0 seconds: C:\Users\fando\Documents\ComfyUI\custom_nodes/comfyui_essentials@1_1_0
2024-11-07 23:22:41,978 - root - INFO -    0.1 seconds: C:\Users\fando\Documents\ComfyUI\custom_nodes/comfyui-kjnodes@1_0_1
2024-11-07 23:22:41,978 - root - INFO -    0.5 seconds: C:\Users\fando\Documents\ComfyUI\custom_nodes/comfyui-videohelpersuite@1_4_0
2024-11-07 23:22:41,978 - root - INFO -    0.5 seconds: C:\Users\fando\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-07 23:22:41,978 - root - INFO -    2.7 seconds (IMPORT FAILED): C:\Users\fando\Documents\ComfyUI\custom_nodes/MaskGCT-ComfyUI
2024-11-07 23:22:41,978 - root - INFO - 
2024-11-07 23:22:41,981 - root - INFO - Setting output directory to: C:\Users\fando\Documents\ComfyUI\output
2024-11-07 23:22:41,981 - root - INFO - Setting input directory to: C:\Users\fando\Documents\ComfyUI\input
2024-11-07 23:22:41,981 - root - INFO - Setting user directory to: C:\Users\fando\Documents\ComfyUI\user
2024-11-07 23:22:41,982 - root - INFO - Starting server

2024-11-07 23:22:41,982 - root - INFO - To see the GUI go to: http://127.0.0.1:8000

**Comment by nylenz** [comment]
same issue

**Comment by cxh612** [comment]
same issue

**Comment by xlibfly** [comment]
same issue
