### ISSUE TITLE
No module named 'models.tts'

### ISSUE THREAD

**Issue by foreverwx129** [AIFSH/MaskGCT-ComfyUI#7]
Traceback (most recent call last):
  File "F:\envs\ComfyUI\ComfyUI\nodes.py", line 2075, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\envs\ComfyUI\ComfyUI\custom_nodes\MaskGCT-ComfyUI\__init__.py", line 25, in <module>
    from models.tts.maskgct.maskgct_utils import *
ModuleNotFoundError: No module named 'models.tts'
装了插件和依赖，还缺个这个是什么原因？

**Comment by Dethic** [comment]
应该是和comfyui的models文件夹冲突了，修改方法：
使用代码编辑器打开该项目，更改models文件夹为mymodels（用编辑器的作用能够同步替换掉项目中各处引用），如果仍有错误，路径上的几个文件夹都加上__init__.py文件，空的就行

**Comment by xlibfly** [comment]
我也是同样的问题
